# Custom Language File for Launcher Customizer

[ejs.app]
title = "Atila Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/WilliamsGon/HunosCraft"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/TxB8buCbcX"

[ejs.settings]
sourceGithubLink = "https://github.com/WilliamsGon/HunosCraft"
supportLink = "https://github.com/WilliamsGon/HunosCraft/issues"

[ejs.welcome]
welcomeHeader = "BIENVENIDO A HUNOSCRAFT"
welcomeDescription = ""
welcomeDescCTA = "Estás a solo unos clics de HunosCraft."
